# Generated by Django 4.2.4 on 2023-08-21 16:46

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(default=None, max_length=64)),
                ('password', models.CharField(max_length=16, null=True)),
                ('room_name', models.CharField(default='Music Room', max_length=30)),
                ('guest_pause', models.BooleanField(default=False)),
                ('guest_add_queue', models.BooleanField(default=False)),
                ('guest_manage_queue', models.BooleanField(default=False)),
                ('guest_chat', models.BooleanField(default=False)),
                ('guest_skip', models.BooleanField(default=False)),
                ('show_lobby', models.BooleanField(default=False)),
                ('private_room', models.BooleanField(default=False)),
                ('current_song', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=api.models.generate_unique_id, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=60)),
                ('verified', models.BooleanField(default=False)),
                ('authenticated', models.BooleanField(default=False)),
                ('room', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserFrontendSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(max_length=150)),
                ('refresh_token', models.CharField(max_length=150)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
