# Generated by Django 4.2.4 on 2023-10-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_id',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
