# Generated by Django 4.2.4 on 2023-08-21 22:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='spot_queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='user_queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=[], size=None),
            preserve_default=False,
        ),
    ]
