# Generated by Django 4.2.4 on 2023-12-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_last_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_chat',
        ),
    ]
