# Generated by Django 4.2.4 on 2023-10-03 22:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_spot_queue_room_user_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spot_queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), size=None),
        ),
    ]
