# Generated by Django 4.2.4 on 2023-12-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.CharField(default='', max_length=32),
        ),
    ]
