# Generated by Django 4.2.4 on 2023-12-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
