# Generated by Django 4.2.4 on 2023-12-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_room_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
