# Generated by Django 4.2.4 on 2023-12-28 14:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bammed_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=64, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='current_song',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='spot_queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), size=None),
        ),
    ]
