services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/backend/backend/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/backend/backend/staticfiles
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: